const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let modelState={presets:[],live:[],selected:''};
let pagesState=[];
async function api(url,opt={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});const text=await r.text();let d;try{d=JSON.parse(text)}catch{d={detail:text}}if(!r.ok)throw new Error(d.detail||`${r.status} ${r.statusText}`);return d}
function toast(s){const t=$('#toast');t.textContent=s;t.style.display='block';clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.style.display='none',4200)}
function badgeState(s){return `<span class="status ${esc(s)}">${esc(s)}</span>`}
function switchTab(name){$$('.tab').forEach(x=>x.classList.toggle('active',x.id===`tab-${name}`));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));$('#pageTitle').textContent={dashboard:'Dashboard',pages:'Facebook Pages',jobs:'Jobs',settings:'Settings'}[name]||name;if(name==='pages')loadPages();if(name==='jobs')loadJobs(true);if(name==='settings'){loadSettings();loadPagesForTest()}}
$$('.nav').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));
async function setFactory(a){try{await api(`/api/factory/${a}`,{method:'POST'});await refreshDashboard();toast(`Factory ${a.toUpperCase()}`)}catch(e){toast(e.message)}}
$('#startBtn').onclick=()=>setFactory('start');$('#pauseBtn').onclick=()=>setFactory('pause');$('#stopBtn').onclick=()=>setFactory('stop');
$('#planBtn').onclick=async()=>{const d=await api('/api/factory/plan-today',{method:'POST'});toast(`Đã đảm bảo ${d.count} slot hôm nay`);refreshDashboard()};
async function refreshDashboard(){const d=await api('/api/dashboard');$('#kTarget').textContent=d.daily_target;$('#kPublished').textContent=d.counts.PUBLISHED||0;$('#kReady').textContent=d.counts.READY||0;$('#kRunning').textContent=(d.counts.RENDERING||0)+(d.counts.SCRIPTING||0)+(d.counts.UPLOADING||0);$('#kFailed').textContent=(d.counts.FAILED||0)+(d.counts.TEST_FAILED||0);const fb=$('#factoryBadge');fb.textContent=d.factory_state;fb.className='badge '+d.factory_state.toLowerCase();$('#autoPublishBadge').textContent=d.auto_publish?'AUTO PUBLISH ON':'AUTO PUBLISH OFF';$('#autoPublishBadge').className='badge '+(d.auto_publish?'running':'muted');$('#pageStats').innerHTML=d.page_stats.map(p=>{const total=p.today_total||0,pub=p.published||0,ready=p.ready||0;const pct=total?Math.round(pub/total*100):0;return `<div class="page-row"><strong>${esc(p.name)}</strong><span>${pub}/${total} published</span><span>${ready} ready</span><div class="progress"><i style="width:${pct}%"></i></div></div>`}).join('');try{const s=await api('/api/settings');const b=$('#llmBadge');b.textContent=s.llm_configured?`${s.llm_provider}: ${s.selected_llm_model||'model?'}`:'LLM FALLBACK';b.className='badge '+(s.llm_configured?'running':'muted')}catch{}await loadJobs(false)}
async function loadJobs(full=false){const d=await api('/api/jobs?limit=120');const rows=d.slice(0,full?120:12);const html=rows.map(j=>`<tr data-job="${j.id}"><td>${full?`<button class="mini" onclick="showJob('${j.id}')">${j.id.slice(0,12)}</button>`:esc(j.page_name)}</td>${full?`<td>${esc(j.page_name)}</td><td>${new Date(j.scheduled_at).toLocaleString()}</td>`:`<td>${new Date(j.scheduled_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</td>`}<td>${esc(j.topic||'—')}</td><td>${esc(j.step)}</td>${full?'':`<td>${j.progress}%</td>`}<td>${badgeState(j.status)}</td><td>${j.output_path?`<button class="mini" onclick="showJob('${j.id}')">Open</button>`:''}</td></tr>`).join('');if(full)$('#jobsFullBody').innerHTML=html;else $('#jobsBody').innerHTML=html}
async function loadPages(){const d=await api('/api/pages');pagesState=d;$('#pagesEditor').innerHTML=d.map(p=>`<div class="page-edit" data-id="${p.id}"><b>#${p.id}</b><input data-k="name" value="${esc(p.name)}"><input data-k="page_id" placeholder="Page ID" value="${esc(p.page_id)}"><input data-k="token_env_key" value="${esc(p.token_env_key)}"><input data-k="slot1" value="${p.slot1}"><input data-k="slot2" value="${p.slot2}"><label class="check compact"><input data-k="enabled" type="checkbox" ${p.enabled?'checked':''}> ON</label><span class="${p.token_configured?'token-ok':'token-no'}">${p.token_configured?'● token':'○ no token'}</span><button class="mini" onclick="savePage(${p.id})">Save</button><button class="mini" onclick="testFacebook(${p.id})">Test FB</button></div>`).join('')}
async function loadPagesForTest(){try{pagesState=await api('/api/pages');const sel=$('#testPage');sel.innerHTML=pagesState.filter(p=>p.enabled).map(p=>`<option value="${p.id}">#${p.id} ${esc(p.name)}</option>`).join('')}catch(e){}}
async function savePage(id){const el=document.querySelector(`.page-edit[data-id="${id}"]`);const body={};el.querySelectorAll('[data-k]').forEach(i=>body[i.dataset.k]=i.type==='checkbox'?i.checked:i.value);try{await api(`/api/pages/${id}`,{method:'PATCH',body:JSON.stringify(body)});toast(`Saved Page #${id}`);loadPages()}catch(e){toast(e.message)}}
async function testFacebook(id){try{const d=await api(`/api/pages/${id}/test-facebook`,{method:'POST'});toast(d.ok?`Facebook OK: ${d.data?.name||''}`:`Facebook lỗi: ${d.error||JSON.stringify(d.data)}`)}catch(e){toast(e.message)}}
async function showJob(id){switchTab('jobs');const d=await api(`/api/jobs/${id}`);const logs=(d.logs||[]).map(x=>`<div>[${x.ts.slice(11,19)}] ${esc(x.level)} ${esc(x.message)}</div>`).join('');$('#jobDetail').innerHTML=`<p><b>${esc(d.page_name)}</b> · ${badgeState(d.status)} · ${d.progress}%</p><p>${esc(d.topic||'')}</p>${d.output_path?`<video class="job-video" controls src="/api/jobs/${id}/video"></video>`:''}<h3>Logs</h3><div class="job-log">${logs||'No logs'}</div>${d.status==='FAILED'?`<button class="btn warn" onclick="retryJob('${id}')">Retry render</button>`:''}`}
async function retryJob(id){await api(`/api/jobs/${id}/retry`,{method:'POST'});toast('Đã đưa job vào retry');loadJobs(true)}
function fillModelSelect(selected){const sel=$('#llmModel');const combined=[];const seen=new Set();for(const m of [...modelState.presets,...modelState.live]){if(!m?.id||seen.has(m.id))continue;seen.add(m.id);combined.push(m)}if(selected&&!seen.has(selected))combined.unshift({id:selected,label:selected,source:'saved'});if(!combined.length)combined.push({id:'',label:'-- chưa có model --'});sel.innerHTML=combined.map(m=>`<option value="${esc(m.id)}" ${m.id===selected?'selected':''}>${esc(m.label||m.id)}${m.source==='preset'?' · preset':''}</option>`).join('')}
async function loadModels(live=true){const box=$('#llmTestResult');try{const d=await api(`/api/llm/models?live=${live?'true':'false'}`);modelState=d;fillModelSelect(d.selected);$('#routerStatus').textContent=d.configured?`${d.provider} READY`:'NO API KEY';$('#routerStatus').className='badge '+(d.configured?'running':'muted');if(d.error)box.textContent=`Model discovery cảnh báo: ${d.error}`;else box.textContent=`${d.presets.length} preset · ${d.live.length} live model`;}catch(e){box.textContent=e.message}}
async function loadSettings(){const d=await api('/api/settings');$('#dailyTarget').value=d.daily_target;$('#autoPublish').checked=d.auto_publish;$('#runtimeInfo').innerHTML=Object.entries(d).filter(([k])=>!['auto_publish','daily_target','selected_llm_model'].includes(k)).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('');await loadModels(true);if(d.selected_llm_model){modelState.selected=d.selected_llm_model;fillModelSelect(d.selected_llm_model)}}
$('#saveSettings').onclick=async()=>{const b={daily_target:+$('#dailyTarget').value,auto_publish:$('#autoPublish').checked,selected_llm_model:$('#llmModel').value};await api('/api/settings',{method:'PATCH',body:JSON.stringify(b)});toast('Đã lưu settings');refreshDashboard()}
$('#refreshModels').onclick=()=>loadModels(true);
$('#testLLMBtn').onclick=async()=>{const model=$('#llmModel').value;const box=$('#llmTestResult');box.textContent=`Đang test ${model}...`;try{const d=await api('/api/llm/test',{method:'POST',body:JSON.stringify({model})});box.innerHTML=`<b>OK</b> · ${esc(d.model)} · ${d.latency_ms} ms<br>${esc(d.output)}`;$('#routerStatus').textContent='LLM OK';$('#routerStatus').className='badge running'}catch(e){box.textContent=`LỖI: ${e.message}`;$('#routerStatus').textContent='LLM ERROR';$('#routerStatus').className='badge stopped'}};
async function createTestVideo(){const pageId=+($('#testPage')?.value||0)||null;const model=$('#llmModel')?.value||null;try{const d=await api('/api/test-video',{method:'POST',body:JSON.stringify({page_row_id:pageId,model})});toast(`Test video đã chạy: ${d.job_id}`);switchTab('jobs');await loadJobs(true);await showJob(d.job_id)}catch(e){toast(e.message)}}
$('#settingsTestVideoBtn').onclick=createTestVideo;$('#testVideoBtn').onclick=async()=>{if(!$('#testPage')?.options?.length){await loadPagesForTest()}if(!$('#llmModel')?.options?.length){await loadModels(false)}createTestVideo()};
function addLive(e){const box=$('#liveLog');const msg=e.message||`${e.type}${e.state?' → '+e.state:''}`;box.innerHTML+=`<div class="live-line"><b>${(e.ts||'').slice(11,19)}</b> ${esc(msg)}</div>`;while(box.children.length>120)box.removeChild(box.firstChild);box.scrollTop=box.scrollHeight}
function connectWS(){const proto=location.protocol==='https:'?'wss':'ws';const ws=new WebSocket(`${proto}://${location.host}/ws`);ws.onopen=()=>{$('#wsDot').classList.add('online');$('#wsText').textContent='Realtime online'};ws.onmessage=e=>{try{const d=JSON.parse(e.data);addLive(d);if(['job_update','factory_state','plan_ready'].includes(d.type))refreshDashboard()}catch{}};ws.onclose=()=>{$('#wsDot').classList.remove('online');$('#wsText').textContent='Reconnect...';setTimeout(connectWS,2000)}}
setInterval(()=>{$('#serverClock').textContent=new Date().toLocaleString()},1000);connectWS();refreshDashboard();loadPagesForTest();loadModels(false);setInterval(refreshDashboard,15000);
